{"name": "test_bank_operations", "status": "broken", "statusDetails": {"message": "TypeError: RemoteConnection.__init__() got an unexpected keyword argument 'resolve_ip'", "trace": "request = <SubRequest 'driver' for <Function test_bank_operations>>\n\n    @pytest.fixture(scope=\"session\")\n    def driver(request):\n        grid_url = \"http://localhost:4444/wd/hub\"\n        capabilities = DesiredCapabilities.CHROME\n    \n        # Установка пользовательских таймаутов\n>       command_executor = RemoteConnection(grid_url, resolve_ip=False, keep_alive=True)\nE       TypeError: RemoteConnection.__init__() got an unexpected keyword argument 'resolve_ip'\n\nconftest.py:14: TypeError"}, "start": 1715185473061, "stop": 1715185473061, "uuid": "ca88a95e-6696-4807-89fd-f6d9f42b28a3", "historyId": "3c20184b1f0f423149f775983a76d9f7", "testCaseId": "3c20184b1f0f423149f775983a76d9f7", "fullName": "tests.test_bank_operations.TestBankOperations#test_bank_operations", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_bank_operations"}, {"name": "subSuite", "value": "TestBankOperations"}, {"name": "host", "value": "Selenium"}, {"name": "thread", "value": "4164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_bank_operations"}]}